# Generated by Django 5.1.5 on 2025-07-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo_epi_api', models.CharField(blank=True, max_length=20, null=True)),
                ('area', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('ppto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ppto_gaf_2025', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('identificado', models.BooleanField(default=False)),
            ],
        ),
    ]
