# Generated by Django 5.1.5 on 2025-07-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='identificado',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ejecutado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='identificado_2025',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='proyectado_p6_2025',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
