# Generated by Django 5.1.5 on 2025-07-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_proyecto_identificado_proyecto_ejecutado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(blank=True, default='Pendiente', max_length=100, null=True),
        ),
    ]
