# Generated by Django 5.1.5 on 2025-07-23 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_proyecto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlujoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROG.', 'Programado'), ('PROG.P6', 'Programado P6'), ('REAL', 'Real')], max_length=20)),
                ('anio', models.IntegerField(default=2025)),
                ('enero', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('febrero', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('marzo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('abril', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mayo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('junio', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('julio', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('agosto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('septiembre', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('octubre', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('noviembre', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('diciembre', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
        ),
    ]
