# Generated by Django 5.1.5 on 2025-07-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.IntegerField(blank=True, null=True)),
                ('codigo_proyecto', models.CharField(max_length=50)),
                ('jefe_proyecto', models.CharField(max_length=100)),
                ('eecc', models.CharField(max_length=100, verbose_name='Empresa Contratista')),
                ('proyecto', models.CharField(max_length=250)),
                ('servicio', models.CharField(max_length=250)),
                ('autor', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('comentario', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Estatus semanal',
                'verbose_name_plural': 'Estatus semanales',
                'ordering': ['-fecha', 'codigo_proyecto'],
            },
        ),
    ]
