# Generated by Django 5.1.5 on 2025-07-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estatussemanal',
            options={},
        ),
        migrations.AlterField(
            model_name='estatussemanal',
            name='autor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estatussemanal',
            name='comentario',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='estatussemanal',
            name='eecc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estatussemanal',
            name='jefe_proyecto',
            field=models.CharField(max_length=50),
        ),
    ]
